/*
 * Aplikasi by : MarufNM
 * FIKOM - Universitas Duta Bangsa
 */
package com.mycompany.sikeusekolah.form;

import javax.swing.JFrame;

/**
 *
 * @author Lamat
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    FormAkun formAkun = new FormAkun();
    FormAngkatan formAngkatan=new FormAngkatan();
    FormJurusan formJurusan = new FormJurusan();
    FormKelas formKelas = new FormKelas();
    FormSIswa formSiswa = new FormSIswa();
    FormBiayaPmb formPmb = new FormBiayaPmb();
    FormBiayaTetap formTetap = new FormBiayaTetap();
    FormBiayaLain formLain = new FormBiayaLain();
    public FormUtama() {
        initComponents();
        
        //fluscreen
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        //menambah FormAkun ke dekstop pane
        

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        menuMaster = new javax.swing.JMenu();
        menuMasterAkun = new javax.swing.JMenuItem();
        menuMasterAngkatan = new javax.swing.JMenuItem();
        menuMasterJurusan = new javax.swing.JMenuItem();
        menuMasterKelas = new javax.swing.JMenuItem();
        menuMasterSiswa = new javax.swing.JMenuItem();
        menuMasterTetap = new javax.swing.JMenuItem();
        menuMasterPmb = new javax.swing.JMenuItem();
        menuMasterLain = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setText("SISTEM KEUANGAN SEKOLAH");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(30, 30, 250, 50);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        menuMaster.setMnemonic('e');
        menuMaster.setText("Master");
        menuMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterActionPerformed(evt);
            }
        });

        menuMasterAkun.setMnemonic('t');
        menuMasterAkun.setText("Akun");
        menuMasterAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterAkunActionPerformed(evt);
            }
        });
        menuMaster.add(menuMasterAkun);

        menuMasterAngkatan.setMnemonic('d');
        menuMasterAngkatan.setText("Angkatan");
        menuMasterAngkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterAngkatanActionPerformed(evt);
            }
        });
        menuMaster.add(menuMasterAngkatan);

        menuMasterJurusan.setMnemonic('p');
        menuMasterJurusan.setText("Jurusan");
        menuMasterJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterJurusanActionPerformed(evt);
            }
        });
        menuMaster.add(menuMasterJurusan);

        menuMasterKelas.setMnemonic('y');
        menuMasterKelas.setText("Kelas");
        menuMasterKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterKelasActionPerformed(evt);
            }
        });
        menuMaster.add(menuMasterKelas);

        menuMasterSiswa.setText("Siswa");
        menuMasterSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterSiswaActionPerformed(evt);
            }
        });
        menuMaster.add(menuMasterSiswa);

        menuMasterTetap.setText("Biaya Tetap");
        menuMasterTetap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterTetapActionPerformed(evt);
            }
        });
        menuMaster.add(menuMasterTetap);

        menuMasterPmb.setText("Biaya PMB");
        menuMasterPmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterPmbActionPerformed(evt);
            }
        });
        menuMaster.add(menuMasterPmb);

        menuMasterLain.setText("Biaya Lain");
        menuMasterLain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterLainActionPerformed(evt);
            }
        });
        menuMaster.add(menuMasterLain);

        menuBar.add(menuMaster);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuMasterAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterAkunActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        desktopPane.add(formAkun);
        formAkun.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMasterAkunActionPerformed

    private void menuMasterKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterKelasActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        desktopPane.add(formKelas);
        formKelas.setVisible(true);        
// TODO add your handling code here:
    }//GEN-LAST:event_menuMasterKelasActionPerformed

    private void menuMasterAngkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterAngkatanActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        desktopPane.add(formAngkatan);
        formAngkatan.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_menuMasterAngkatanActionPerformed

    private void menuMasterJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterJurusanActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        desktopPane.add(formJurusan);
        formJurusan.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_menuMasterJurusanActionPerformed

    private void menuMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMasterActionPerformed

    private void menuMasterSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterSiswaActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        desktopPane.add(formSiswa);
        formSiswa.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_menuMasterSiswaActionPerformed

    private void menuMasterPmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterPmbActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        desktopPane.add(formPmb);
        formPmb.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_menuMasterPmbActionPerformed

    private void menuMasterTetapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterTetapActionPerformed
       desktopPane.removeAll();
       desktopPane.repaint();
       desktopPane.add(formTetap);
       formTetap.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_menuMasterTetapActionPerformed

    private void menuMasterLainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterLainActionPerformed
       desktopPane.removeAll();
       desktopPane.repaint();
       desktopPane.add(formLain);
       formLain.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_menuMasterLainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenuItem menuMasterAkun;
    private javax.swing.JMenuItem menuMasterAngkatan;
    private javax.swing.JMenuItem menuMasterJurusan;
    private javax.swing.JMenuItem menuMasterKelas;
    private javax.swing.JMenuItem menuMasterLain;
    private javax.swing.JMenuItem menuMasterPmb;
    private javax.swing.JMenuItem menuMasterSiswa;
    private javax.swing.JMenuItem menuMasterTetap;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
