/*
 * Aplikasi by : MarufNM
 * FIKOM - Universitas Duta Bangsa
 */
package com.mycompany.sikeusekolah.form;
    import com.mycompany.sikeusekolah.Koneksi;
    import java.sql.ResultSet;
    import java.time.LocalDateTime;
    import java.time.format.DateTimeFormatter;
    import javax.swing.JOptionPane;
    import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Lamat
 */
public class FormBiayaPmb extends javax.swing.JInternalFrame {
    Koneksi kon;
    ResultSet rs;
    String mode;
    /**
     * Creates new form FormBiayaPmb
     */
    public FormBiayaPmb() {
        initComponents();
         kon = new Koneksi();
         tampilData("");
         cbangkatan();
         cbjurusan();
         cbakun();
    }
     public void cbangkatan(){
     try{
         String sql="select * from angkatan";
         rs = kon.perintah.executeQuery(sql);
         cbangkatan.addItem("-Pilih Angkatan-");
         while (rs.next()) {
             cbangkatan.addItem(rs.getString("tahun"));
         }
        }catch(Exception e){
            System.err.println("Gagal Tampil data: "+e.getMessage());
       }
    }
     
     public void cbjurusan(){
     try{
         String sql="select * from jurusan";
         rs = kon.perintah.executeQuery(sql);
         cbjurusan.addItem("-Pilih Jurusan-");
         while (rs.next()) {
             cbjurusan.addItem(rs.getString("id"));
         }
        }catch(Exception e){
            System.err.println("Gagal Tampil data: "+e.getMessage());
       }
    }
     public void cbakun(){
     try{
         String sql="select * from akun";
         rs = kon.perintah.executeQuery(sql);
         cbakun.addItem("-Pilih Akun-");
         while (rs.next()) {
             cbakun.addItem(rs.getString("kode"));
         }
        }catch(Exception e){
            System.err.println("Gagal Tampil data: "+e.getMessage());
       }
    }
     
     private void tampilData(String filter){
        Object[] judulKolom = {"No","ID","Akun","Nama Biaya","Jumlah","Tahun Angkatan","Gelombang","Jurusan"};
        DefaultTableModel modelSiswa = new DefaultTableModel(null,judulKolom);
        dataPmb.setModel(modelSiswa);

        try{
           String sql="select * from biaya_pmb where id like '%"+filter+"%' or akun_id like '%"+filter+"%'" ;
            rs = kon.perintah.executeQuery(sql);
            int no = 0;
            while (rs.next()) {
                no++;
                String txtId =rs.getString("id");
                String txtAkun_id =rs.getString("akun_id");
                String txtNama_biaya =rs.getString("nama_biaya");
                String txtJumlah =rs.getString("jumlah");
                String txtAngkatan =rs.getString("tahun_angkatan");
                String txtGelombang =rs.getString("gelombang");
                String txtJurusan =rs.getString("jurusan");
             
                String[] barisBaru = {Integer.toString(no), txtId, txtAkun_id, txtNama_biaya, txtJumlah, txtAngkatan, txtGelombang, txtJurusan};
                modelSiswa.addRow(barisBaru);
            }
        }catch(Exception salahe){
            System.err.println("Gagal Tampil data: "+salahe.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogPMB = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        cbakun = new javax.swing.JComboBox<>();
        biaya = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        cbangkatan = new javax.swing.JComboBox<>();
        cbjurusan = new javax.swing.JComboBox<>();
        gelombang = new javax.swing.JTextField();
        simpan = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataPmb = new javax.swing.JTable();
        tambah = new javax.swing.JToggleButton();
        edit = new javax.swing.JToggleButton();
        hapus = new javax.swing.JToggleButton();
        cari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("ID");

        jLabel3.setText("Akun");

        jLabel4.setText("Nama Biaya");

        jLabel5.setText("Jumlah");

        jLabel6.setText("Angkatan");

        jLabel7.setText("Gelombang");

        jLabel8.setText("Jurusan");

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogPMBLayout = new javax.swing.GroupLayout(dialogPMB.getContentPane());
        dialogPMB.getContentPane().setLayout(dialogPMBLayout);
        dialogPMBLayout.setHorizontalGroup(
            dialogPMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPMBLayout.createSequentialGroup()
                .addGroup(dialogPMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogPMBLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(dialogPMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(23, 23, 23)
                        .addGroup(dialogPMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbakun, 0, 193, Short.MAX_VALUE)
                            .addComponent(biaya)
                            .addComponent(jumlah)
                            .addComponent(cbangkatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbjurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gelombang)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dialogPMBLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(simpan)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        dialogPMBLayout.setVerticalGroup(
            dialogPMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPMBLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(dialogPMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogPMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbakun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogPMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(biaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogPMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogPMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cbangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogPMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(gelombang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogPMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(simpan)
                .addGap(28, 28, 28))
        );

        dataPmb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dataPmb);

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        jLabel1.setText("Cari");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(edit)
                    .addComponent(hapus)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        mode="tambah";
        id.setText(null);
        cbakun.setSelectedItem(null);
        biaya.setText(null);
        jumlah.setText(null);
        cbangkatan.setSelectedItem(null);
        gelombang.setText(null);
        cbjurusan.setSelectedItem(null);
        id.setEnabled(true);
        dialogPMB.setTitle("Form Biaya PMB - Tambah");
        dialogPMB.pack();
        dialogPMB.setLocationRelativeTo(null);
        dialogPMB.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_tambahActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
    int baris_index = dataPmb.getSelectedRow();
        if(baris_index >= 0) {
            mode="edit";
            String id_pilih = (dataPmb.getModel().getValueAt(baris_index, 1).toString());
            try {
                String sql="select * from biaya_pmb where id='"+id_pilih+"'";
                rs = kon.perintah.executeQuery(sql);
                if (rs.next()) {
                    String txtId = rs.getString("id");
                    String txtAkun_id= rs.getString("akun_id");
                    String txtNama_biaya = rs.getString("nama_biaya");
                    String txtJumlah = rs.getString("jumlah");
                    String txtAngkatan = rs.getString("tahun_angkatan");
                    String txtGelombang = rs.getString("gelombang");
                    String txtJurusan = rs.getString("jurusan");
                    
                    id.setText(txtId);
                    cbakun.setSelectedItem(txtAkun_id);
                    biaya.setText(txtNama_biaya);
                    jumlah.setText(txtJumlah);
                    cbangkatan.setSelectedItem(txtAngkatan);
                    cbjurusan.setSelectedItem(txtJurusan);
                    gelombang.setText(txtGelombang);
                    
                    
                    id.setEnabled(false);
                    dialogPMB.setTitle("Form Biaya PMB - Edit");
                    dialogPMB.pack();
                    dialogPMB.setLocationRelativeTo(null);
                    dialogPMB.setVisible(true);
                }
            } catch (Exception salahe) {
                System.err.println("Gagal Tampil data: "+salahe.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Belum ada data yang dipilih");
        }          // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int baris_index = dataPmb.getSelectedRow();
        if (baris_index >= 0) {
            int jwb = JOptionPane.showConfirmDialog(this, "Yakin mau hapus data ini ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if(jwb == JOptionPane.YES_OPTION) {
                String id_pilih = (dataPmb.getModel().getValueAt(baris_index, 1).toString());
                try {
                    String sql="delete from biaya_pmb where id='"+id_pilih+"'";
                    kon.perintah.execute(sql);
                    tampilData("");
                } catch (Exception salahe) {
                    System.err.println("Gagal Tampil data: "+salahe.getMessage());
                }
            }
        }else {
            JOptionPane.showMessageDialog(this, "Belum ada data yang dipilih");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        String txtCari = cari.getText();
        tampilData(txtCari);        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        String txtId = id.getText();      
        String txtAkun_id = String.valueOf(cbakun.getSelectedItem());
        String txtNama_biaya = biaya.getText();
        String txtJumlah = jumlah.getText();
        String txtAngkatan = String.valueOf(cbangkatan.getSelectedItem());
        String txtGelombang = gelombang.getText();       
        String txtJurusan =  String.valueOf(cbjurusan.getSelectedItem());
 
        String sql = "";
        
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter format = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String waktu_sekarang = now.format(format);
        
        if (mode == "tambah") {
            sql = "insert into biaya_pmb values ("
                + "'" + txtId +"',"
                + "'" + txtAkun_id +"',"
                + "'" + txtNama_biaya +"',"
                + "'" + txtJumlah +"',"
                + "'" + txtAngkatan +"',"
                + "'" + txtGelombang +"',"
                + "'" + txtJurusan +"',"
                + "'" + waktu_sekarang +"',"
                + "'" + waktu_sekarang +"',"
                 + "null"
                + ")";
        } else {
            sql = "update biaya_pmb set akun_id ='"+txtAkun_id+"',"
                + "nama_biaya='"+ txtNama_biaya +"',"
                + "jumlah='"+ txtJumlah +"',"
                + "tahun_angkatan='"+ txtAngkatan +"',"
                + "gelombang='"+ txtGelombang +"',"
                + "jurusan='"+ txtJurusan +"',"
                
                + "updated_at='"+waktu_sekarang+"'"
                + "where id='"+txtId+"'";
        }
        
       try {
            kon.perintah.execute(sql);
            dialogPMB.setVisible(false);
            tampilData("");
        } catch (Exception salahe) {
            System.err.println("Gagal Tampil data: "+salahe.getMessage());
            JOptionPane.showConfirmDialog(this, "Gagal Simpan");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biaya;
    private javax.swing.JTextField cari;
    private javax.swing.JComboBox<String> cbakun;
    private javax.swing.JComboBox<String> cbangkatan;
    private javax.swing.JComboBox<String> cbjurusan;
    private javax.swing.JTable dataPmb;
    private javax.swing.JDialog dialogPMB;
    private javax.swing.JToggleButton edit;
    private javax.swing.JTextField gelombang;
    private javax.swing.JToggleButton hapus;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JToggleButton simpan;
    private javax.swing.JToggleButton tambah;
    // End of variables declaration//GEN-END:variables
}
